name: Build
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - ".github/**"
      - "SOG_Framework/core/main/script_version.hpp"
      - "tools/**"
      - ".gitignore"
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout the source code
        uses: actions/checkout@main
        with:
          ref: development
          token: ${{ secrets.ACTION_TOKEN }}
          
      - name: Bump version
        id: bump-version
        run: python3 tools/version_bumper.py increment_build push_commit
        
      - name: Run a multi-line script
        uses: actions/upload-artifact@v2
        with:
          name: SOG_Framework_v${{ steps.bump-version.outputs.VERSION }}
          path: |
            SOG_Framework/
            cba_settings.sqf
            description.ext
            
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2
        
      - name: Release Drafter
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
