name: Build

on:
<<<<<<< HEAD
    push:
        branches:
            - master
        paths-ignore:
            - ".github/**"
            - "SOG_Framework/core/main/script_version.hpp"
            - "tools/**"
            - ".editorconfig"
            - ".gitignore"
=======
	push:
		branches:
			- master
		paths-ignore:
			- ".github/**"
			- "SOG_Framework/core/main/script_version.hpp"
			- "tools/**"
			- ".gitignore"
>>>>>>> 14f5b18bbfb9d7641e064ae87a4353d2ee823cea

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the source code
              uses: actions/checkout@master
              with:
                  ref: master
                  token: ${{ secrets.ACTION_TOKEN }}

            - name: Bump version
              id: bump-version
              run: python3 tools/version_bumper.py increment_build push_commit

            - name: Upload artifact
              uses: actions/upload-artifact@v2
              with:
                  name: MalFramework_v${{ steps.bump-version.outputs.VERSION }}
                  path: |
                      SOG_Framework/
                      cba_settings.sqf
                      description.ext
                      LICENSE
                      README.md

<<<<<<< HEAD
    draft-release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the source code
              uses: actions/checkout@v2

            - name: Release Drafter
              uses: release-drafter/release-drafter@v5
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
=======
			- name: Release Drafter
				uses: release-drafter/release-drafter@v5
				env:
					GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
>>>>>>> 14f5b18bbfb9d7641e064ae87a4353d2ee823cea
